nelmio_api_doc:
  name: API
  sandbox:
    authentication:
      name:           Authorization
      delivery:       http
      type:           bearer

  cache:
    enabled:            false
    file:               '%kernel.cache_dir%/api-doc.cache'