parameters:
    locale: 'en'
    app.logout_listener.class: App\Listener\LogoutListener
    app.authentication_success_handler.class: App\Security\ApiAuthentificatorHandler

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    app.logout.listener:
        class: "%app.logout_listener.class%"
        arguments:
            - "@doctrine.orm.default_entity_manager"

    app.api_authentication_success_handler:
        public: true
        class: "%app.authentication_success_handler.class%"
        tags:
            - { name: monolog.logger, channel: security }

